services:
  postgres:
    image: "postgres"
    container_name: postgres
    restart: always
    ports:
      - "5431:5432"
    volumes:
      - E:\PostgressData\Data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "@Tinus"
      PGDATA: "/var/lib/postgresql/data/pgdata"

  validator:
    build:
      context: /Validator
      dockerfile: Dockerfile
    image: "validator:v0.0.5"
    container_name: validator
    ports:
      - "8001:8001"
#    environment:
#      - "SPRING_PROFILES_ACTIVE=docker"
#    depends_on:
#      - postgres

  beautifier:
    build:
      context: /Beautifier
      dockerfile: Dockerfile
    image: "beautifier:v0.0.5"
    container_name: beautifier
    ports:
      - "8002:8002"
#    environment:
#      - "SPRING_PROFILES_ACTIVE=docker"
#    depends_on:
#      - postgres
